# Generated by Django 6.1 on 2026-08-18 18:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DBTaskResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_path", models.CharField(max_length=255)),
                ("args_json", models.JSONField(default=list)),
                ("kwargs_json", models.JSONField(default=dict)),
                (
                    "queue_name",
                    models.CharField(db_index=True, default="default", max_length=100),
                ),
                ("priority", models.SmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("RUNNING", "Running"),
                            ("SUCCESSFUL", "Successful"),
                            ("FAILED", "Failed"),
                        ],
                        default="READY",
                        max_length=10,
                    ),
                ),
                ("run_after", models.DateTimeField(db_index=True)),
                ("enqueued_at", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_retries", models.PositiveIntegerField(default=0)),
                (
                    "delivery_guarantee",
                    models.CharField(
                        choices=[
                            ("AT_LEAST_ONCE", "At least once"),
                            ("AT_MOST_ONCE", "At most once"),
                        ],
                        default="AT_LEAST_ONCE",
                        max_length=20,
                    ),
                ),
                ("errors", models.JSONField(blank=True, default=list)),
                ("return_value", models.JSONField(blank=True, null=True)),
                ("worker_ids", models.JSONField(blank=True, default=list)),
                (
                    "claimed_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "queue_name", "-priority", "run_after"],
                        name="werker_claim_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PeriodicTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("task_path", models.CharField(max_length=255)),
                ("args_json", models.JSONField(default=list)),
                ("kwargs_json", models.JSONField(default=dict)),
                (
                    "schedule_kind",
                    models.CharField(
                        choices=[
                            ("CRON", "Cron expression"),
                            ("INTERVAL", "Fixed interval"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "interval_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("timezone", models.CharField(default="UTC", max_length=100)),
                ("queue_name", models.CharField(default="default", max_length=100)),
                ("priority", models.SmallIntegerField(default=0)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "catchup",
                    models.BooleanField(
                        default=False,
                        help_text="If the worker was down past a fire time: False (default) skips to the next future occurrence, True fires once immediately for the missed occurrence.",
                    ),
                ),
                ("next_run_at", models.DateTimeField(db_index=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "claimed_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["enabled", "next_run_at"], name="werker_schedule_idx"
                    )
                ],
            },
        ),
    ]
